import React from "react";
import Navbar from "../Layouts/Navbar Creator/Navbar";
import Footer from "../Footer/Footer";
import "./Static.css";

const TermsObj = [
  {
    title: "Eligibility",
    points: [
      "You must be at least 18 years old"
    ],
  },
  {
    title: "Account Registration",
    points: [
      "You must provide accurate and complete information during the registration process",
      "You are responsible for maintaining the confidentiality of your account credentials and for any activities that occur under your account.",
      "You agree to notify us immediately of any unauthorized use or breach of security related to your account.",
    ],
  },
  {
    title: "Creator Guidelines",
    points: [
      "As a creator of anchors, you agree to comply with our guidelines and policies regarding content creation, quality standards, and community guidelines.",
      "You bear full responsibility for the content you generate and distribute on this platform, and ensure that it complies with all relevant laws regarding copyright, intellectual property, and other applicable regulations."
    ],
  },
  {
    title: "User Guidelines",
    points: [
      `The Platform facilitates the connection between service providers ("Creators") and users ("Users"). Users can browse and avail themselves of the services provided by Creators. You agree to use the services only for lawful purposes and in accordance with these Terms.`,
      "While the Platform endeavors to provide accurate and up-to-date information, we do not guarantee the accuracy or completeness of the services listed by Creators. Users are responsible for evaluating the services, the Creator's qualifications, and the appropriateness for their needs."
    ],
  },
  {
    title: "Platform Fees",
    points: [
      "anchors charges a platform fee of 10% on the total earnings generated by creators through the platform.",
      "The platform fee may be subject to change, and any updates will be communicated to you in advance."
    ],
  },
  {
    title: "Payment Terms",
    points: [
      "Earnings from your creator activities will be paid out on a monthly basis.",
      "Payment will be made to the bank account provided by you during the registration process.",
      "Anchors reserves the right to withhold or delay payments in case of suspected fraudulent activities or violation of our terms and conditions."
    ],
  },
  {
    title: "Termination",
    points: [
      "Anchors reserves the right to suspend or terminate your account and access to the platform at any time, for any reason, without prior notice.",
      "You may also request the termination of your account by contacting anchor support.",
      "Users may provide feedback and reviews for services they have used. Feedback should be accurate and constructive. The Platform reserves the right to moderate or remove content or the account that violates these Terms.",
      "You agree not to engage in any activity that may harm the Platform, its users, or its creators. This includes but is not limited to, posting false or misleading information, engaging in fraudulent behavior, spamming, or violating intellectual property rights."
    ],
  },
  {
    title: "Updates and Modifications",
    points: [
      "Anchors may update or modify these terms and conditions from time to time. Any changes will be communicated to you via email or by posting a notice on the platform."
    ],
  },
  {
    title: "Governing Law",
    points: [
      "These terms and conditions shall be governed by and construed in accordance with the laws of India."
    ],
  },
];

const Terms = () => {
  return (
    <>
      <Navbar noAccount={true} backgroundDark={true} />

      <div className="static_pages_outer_wrapper">
        <h1 className="static_page_text_01">Terms and Conditions</h1>
        <section>
          By signing up on anchors, you agree to the following
          terms and conditions:
          <br />
          <br />
          {TermsObj?.map((e, i) => {
            return (
              <div key={i}>
                <h2 className="static_page_text_02">{`${i + 1}. ${
                  e?.title
                }:`}</h2>
                <ul>
                  {e?.points?.map((point, index) => {
                    return <li key={`point${index}`}>{point}</li>;
                  })}
                </ul>
              </div>
            );
          })}
          <br />
          <br />
          By accessing and using the anchors Platform, you acknowledge that you
          have read and understood this Privacy Policy and agree to the
          collection, use, and disclosure of your personal information as
          described herein.
        </section>
      </div>

      <Footer />
    </>
  );
};

export default Terms;
