import mixpanel from "mixpanel-browser";
import React, { useEffect } from "react";
import { SuperSEO } from "react-super-seo";
import "./Privacy.css";
import Navbar from "../Layouts/Navbar Creator/Navbar";

function TermsOfUse() {
  // Visited page mix panel
  useEffect(() => {
    mixpanel.track("Visited Privacy Policy");
  }, []);

  return (
    <>
      <Navbar noAccount={true} whiteTheme = {true}/>
      <div className="privacy_policy">
        <h1>Creator Terms and Conditions</h1>
        <section>
          By signing up as a creator on anchors, you agree to the following
          terms and conditions:
          <h2>1. Eligibility:</h2>
          <ul>
            <li>
              You must be at least 18 years old to become a creator on anchors.
            </li>
          </ul>
          <h2>2. Account Registration:</h2>
          <ul>
            <li>
              You must provide accurate and complete information during the
              registration process.
            </li>
            <li>
              You are responsible for maintaining the confidentiality of your
              account credentials and for any activities that occur under your
              account.
            </li>
            <li>
              You agree to notify us immediately of any unauthorized use or
              breach of security related to your account.
            </li>
          </ul>
          <h2>3. Creator Guidelines:</h2>
          <ul>
            <li>
              As a creator of anchors, you agree to comply with our guidelines
              and policies regarding content creation, quality standards, and
              community guidelines.
            </li>
            <li>
              You bear full responsibility for the content you generate and
              distribute on this platform, and ensure that it complies with all
              relevant laws regarding copyright, intellectual property, and
              other applicable regulations.
            </li>
          </ul>
          <h2>4. Platform Fees:</h2>
          <ul>
            <li>
              anchors charges a platform fee of 10% on the total earnings
              generated by creators through the platform
            </li>
            <li>
              The platform fee may be subject to change, and any updates will be
              communicated to you in advance.
            </li>
          </ul>
          <h2>5. Payment Terms:</h2>
          <ul>
            <li>
              Earnings will be calculated based on the revenue generated from
              your content on anchors.
            </li>
            <li>
              Payments will be made on a regular basis, as per the payment
              schedule specified by anchors.
            </li>
            <li>
              You are responsible for providing accurate payment information to
              ensure timely and accurate payments.
            </li>
          </ul>
          <h2>6. Intellectual Property:</h2>
          <ul>
            <li>
              You retain the rights to the content you create and share on
              anchors.
            </li>
            <li>
              By using anchors, you grant anchors a non-exclusive, worldwide,
              royalty-free license to use, reproduce, modify, adapt, publish,
              and distribute your content for promotional purposes related to
              the platform.
            </li>
          </ul>
          <h2>7. Termination:</h2>
          <ul>
            <li>
              anchors reserves the right to suspend or terminate your account
              and access to the platform at any time, for any reason, without
              prior notice.
            </li>

            <li>
              You may also request the termination of your account by contacting
              anchors support.
            </li>
          </ul>
          <h2>8. Updates and Modifications:</h2>
          <ul>
            <li>
              anchors may update or modify these terms and conditions from time
              to time. Any changes will be communicated to you via email or by
              posting a notice on the platform.
            </li>
          </ul>
          <h2>9. Governing Law:</h2>
          <ul>
            <li>
              These terms and conditions shall be governed by and construed in
              accordance with the laws of India
            </li>
          </ul>
          <br />
          <br />
          It is crucial that you thoroughly read and comprehend the terms and
          conditions stated by AlphaHive Anchors Pvt Ltd. By proceeding with the
          sign-up process, you acknowledge your understanding of these terms and
          conditions and willingly accept to be legally bound by them.
        </section>
      </div>
      <SuperSEO title="Anchors - Terms of Use" />
    </>
  );
}

export default TermsOfUse;
